### ISSUE TITLE
Protokube is not found

### ISSUE THREAD

**Issue by Mhs-220** [cicdteam/nvidia-device-plugin#1]
Hi
when I try to use your container in execContainer hook, I face an issue that I don't have `protokube.service` and the script failed to install `nvidia-docker`. should I have `protokube.service`?
P.S.1: When I remove `systemctl stop protokube` and `systemctl start protokube` code works very well.
P.S.2: My cluster setup in AWS with kops.

**Comment by cicdteam** [comment]
@Mhs-220 Hi!

That;s strange... I just re-initialized new cluster on AWS by latest kops (1.16.0) and havn't seen such problems. 

Can you share more details about your cluster ? what kops options were used ?

**Comment by Mhs-220** [comment]
My cluster initialized about one year ago with k8s 1.14 (if I remember correctly).
I have an instance group called `gpunodes` alongside master and nodes. The Protokube service is already available on the master instance group but not in the nodes nor the gpunodes.
My cluster config with these options on AWS:
```yaml
 kubeScheduler:
    usePolicyConfigMap: true
 kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
```
Now my cluster is using the latest version of Kops and k8s but sadly the protokube still not visible in my nodes. Do you need more information?
